spring:
  application:
    name: eureka-service
    
server:
  port: 8302

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: #important part, without this clients will get connection refused exception
      defaultZone: http://localhost:8302/eureka  
  server:
      waitTimeInMsWhenSyncEmpty: 0
 
      
     
zuul:
  # Service will be mapped under uri /api
  prefix: /api
  routes:
    db-service:
      path:/db-service/**
      url:http://localhost:8300
    stock-service:
      path:/stock-service/**
      url:http://localhost:8301
      